"""Compile the user-supplied inventory without altering manual alias overrides."""

import argparse
from collections import defaultdict
from pathlib import Path

import yaml

from wow_hue.config import load_config, normalize, read_yaml
from wow_hue.location_ocr import Matcher, OCRConfig

# Source group names differ from the existing lighting catalog. Dire Maul has
# three wing profiles; require known wing context rather than choosing one.
PARENT_GROUPS = {
    "Ahn'Qiraj": ["temple_of_ahn_qiraj"],
    "Dire Maul": ["dire_maul_east", "dire_maul_west", "dire_maul_north"],
}


def build(source, catalog, manual):
    groups = defaultdict(dict)
    report = {
        "source_records": 0,
        "unresolved_parents": [],
        "canonical_name_collisions": [],
        "manual_overrides": [],
    }
    manual_names = {normalize(n) for n in manual["location_aliases"]}
    canonical_names = {
        normalize(name): key for key, p in catalog.profiles.items() for name in p.names
    }
    for section, parents in source.items():
        if section not in {
            "classic",
            "classic_battlegrounds",
            "classic_instance_subzones",
        } or not isinstance(parents, dict):
            raise ValueError(f"Invalid source section: {section}")
        for parent, data in parents.items():
            if not isinstance(data, dict) or not isinstance(data.get("subzones"), dict):
                raise TypeError(f"Invalid parent inventory: {parent}")
            target = catalog.resolve(parent)
            targets = PARENT_GROUPS.get(parent, [target] if target else [])
            if any(t not in catalog.profiles for t in targets):
                raise ValueError(f"Missing configured parent-group profile: {parent}")
            for area_id, label in data["subzones"].items():
                if (
                    not isinstance(area_id, int)
                    or area_id <= 0
                    or not isinstance(label, str)
                    or not normalize(label)
                ):
                    raise ValueError(f"Invalid subzone under {parent}")
                report["source_records"] += 1
                record = {"label": label, "parent": parent, "area_id": area_id}
                if not targets:
                    report["unresolved_parents"].append(record)
                    continue
                text = normalize(label)
                if text in canonical_names:
                    if canonical_names[text] not in targets:
                        report["canonical_name_collisions"].append(record)
                    continue
                for resolved in targets:
                    groups[text][resolved] = label
    aliases = {}
    for text, parents in sorted(groups.items()):
        label = next(iter(parents.values()))
        entries = [{"parent": catalog.profiles[parent].names[0]} for parent in sorted(parents)]
        aliases[label] = entries[0] if len(entries) == 1 else entries
        if text in manual_names:
            report["manual_overrides"].append(label)
    imported = {"location_aliases": aliases}
    merged = {
        name: definition
        for name, definition in aliases.items()
        if normalize(name) not in manual_names
    }
    merged.update(manual["location_aliases"])
    Matcher(catalog, {"location_aliases": merged}, OCRConfig())
    report["generated_labels"] = len(aliases)
    report["parent_group_mappings"] = PARENT_GROUPS
    report["scoped_labels"] = sum(isinstance(v, list) for v in aliases.values())
    return imported, report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=Path("config/app.yaml"))
    args = parser.parse_args()
    app, catalog = load_config(args.config)
    base = args.config.resolve().parent
    ocr_path = base / app.ocr
    ocr = OCRConfig.model_validate(read_yaml(ocr_path))
    source = read_yaml(base / "subzones.source.yaml")
    imported, report = build(source, catalog, read_yaml(ocr_path.parent / ocr.aliases_file))
    (base / "subzones.generated.yaml").write_text(
        "# Generated by tools/build_subzones.py. Edit location_aliases.yaml for overrides.\n"
        + yaml.safe_dump(imported, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    (base / "subzones.import-report.yaml").write_text(
        yaml.safe_dump(report, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    print(
        f"{report['source_records']} source records; {report['generated_labels']} labels; {report['scoped_labels']} scoped names; {len(report['unresolved_parents'])} unresolved parent records; {len(report['canonical_name_collisions'])} canonical-name collisions"
    )


if __name__ == "__main__":
    main()
